### ISSUE TITLE
Questions: The SBOM check failed when the latest release provides the asset sbom.tar.gz

### ISSUE THREAD

**Issue by zhzhuang-zju** [cncf/clomonitor#1562] opened 2024-08-15 03:04 UTC
Refer to [checks sbom](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom), sbom check passes if the latest release on Github includes an asset which name contains `sbom`. [Karmada](https://github.com/karmada-io/karmada) has provided the asset `sbom.tar.gz` in its latest release `v1.10.3`(https://github.com/karmada-io/karmada/releases/tag/v1.10.3), but still failed in [sbom check](https://clomonitor.io/projects/cncf/karmada#karmada). Could someone explain why this is happening? Thanks a lot~

**Comment by tegioz** [comment] 2024-08-15 08:40
Hi @zhzhuang-zju 👋 

I think the problem is related to the latest release found by CLOMonitor, not the sbom check. If you click on the recent release link in the Karmada page in the CLOMonitor UI, you'll notice that it takes you to the `v1.8.6` release, not to `v1.10.3` as expected. That version doesn't include the sbom asset, so the check doesn't pass.

This may be happening due to the way we are fetching the releases. We get the [last 30 releases, sorted by the creation date (descending)](https://github.com/cncf/clomonitor/blob/06c6e048c82b90e810224dcb1ad66b1e6049765b/clomonitor-core/src/linter/checks/datasource/github/md.graphql#L51-L63). But maybe, `v1.10.3`, `v1.9.5` and `v1.8.6` were released approximately at the same time, and the creation date isn't good enough to pick the latest.

I think we can fix this getting the latest release in a different way ([the repo has a latest release field](https://docs.github.com/en/graphql/reference/objects#repository)), we'll look into it 🙂

**Comment by tegioz** [comment] 2024-08-15 08:54
Quick update: I've just remembered why we weren't already using the latest release field 😅

Sometimes the latest release is marked as pre-release, and we don't count that one as an official release. That's why we need to get some and pick the most recent one that isn't a pre-release.

I think we'll try to rely on the latest release field as the first option if it points to a version that isn't a pre-release (this should fix this case), and otherwise fallback to the current mechanism.

**Closed** 2024-08-15 13:57 UTC
Labels: bug, area/core
